import Head from 'next/head'
import ProductCard from '../src/components/cards/ProductCard'
import Layout from '../src/components/layouts/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Benny Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className='container mx-auto py-10 px-6 md:px-0'>
          <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8'>
            {
              [1, 2, 3, 4, 5, 6].map((item, index) => (
                <ProductCard key={index} />
              ))
            }
          </div>
        </div>
      </Layout>
    </>
  )
}
