import Head from 'next/head'
import Layout from '../src/components/layouts/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Benny Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h2 className="text-slate-500 font-medium">Hello Benny Shop</h2>
      </Layout>
    </>
  )
}
